#spring.application.name=capstone-web
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: capstone
    password: capstone_pw
  jpa:
    hibernate:
      ddl-auto: update       # 초기엔 편의상 update, 운영은 migration 권장
    show-sql: true
    properties:
      hibernate.format_sql: true

ai:
  base-url: http://127.0.0.1:8000
  endpoints:
    predict: /predict

minio:
  endpoint: http://127.0.0.1:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: capstone
  presign-expire-seconds: 3600