#spring.application.name=capstone-web
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: capstone
    password: capstone_pw
  jpa:
    hibernate:
      ddl-auto: update       # 초기엔 편의상 update, 운영은 migration 권장
    show-sql: true
    properties:
      hibernate.format_sql: true

ai:
  base-url: http://127.0.0.1:8000
  timeout-seconds : 25
  threshold-default : 0.5
  endpoints: #FastAPI 입장에서의 엔드포인트
    predict: /predict
    heatmap: /heatmaps/{heatmapId} # <- 임시 리소스 ID

minio:
  endpoint: http://127.0.0.1:9000
  access-key: minioadmin
  secret-key: minioadmin
  raw-bucket: capstone-raw # 원본 이미지 저장 버킷
  heatmaps-bucket: capstone-heatmaps # 히트맵/프리뷰 저장 버킷
  presign-expire-seconds: 3600